### ISSUE TITLE
Build the Game Board background

### ISSUE THREAD

**Issue by clicksave** [keep-starknet-strange/tsubasa#17]
We have a nice looking soccer BG that needs to be constructed. This serves as the background of the game board. 

<img width="1675" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/cb0afc5f-5043-46de-921c-5333a1e0ae3e">

---

Lets make it responsive as well.

Note: the soccer board in the center has a max & min widths, beyond that its max size stops expanding and is center aligned on the page.

https://github.com/keep-starknet-strange/tsubasa/assets/3332646/5c41c9e4-35b9-4f78-940e-2acdb1a21b51

--- 

On mobile the orientation of the field changes

<img width="993" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/e3292058-15e3-4df0-a47a-059ca54f7e40">

https://github.com/keep-starknet-strange/tsubasa/assets/3332646/f3ebc7b4-4218-4c32-b4b1-f6e4ee1ea2e8

Note: the mobile version of the field rests in a specific section on the game board

<img width="518" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/6fbf9ef1-161e-44d4-8e41-4f26c58ab238">

---

**Resources**

[Desktop](https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=94%3A15040&mode=design&t=XTyAVzOoyY9iAsMt-1) - [Mobile](https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=136%3A30842&mode=design&t=XTyAVzOoyY9iAsMt-1)

**Comment by ayushtom** [comment]
https://github.com/keep-starknet-strange/tsubasa/pull/40

**Comment by ayushtom** [comment]
#40
