### ISSUE TITLE
Build the Scoreboard

### ISSUE THREAD

**Issue by clicksave** [keep-starknet-strange/tsubasa#18]
Stop me if this is too clever. We had an idea to communicate all game state via the scoreboard

This thing.. that big black box at the top center of the game board. 

<img width="1615" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/76e3fe21-5413-475e-8ccf-409044112389">

<img width="690" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/63308f9a-2268-4dc0-a2c8-cf76ec79a97f">

---

We can use it a bunch of different ways, but primarily it will communicate the game score 

<img width="943" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/379d2574-6158-4d0b-9cef-9295e4e3594d">

---

If someone scores a goal it can change to reflect that

https://github.com/keep-starknet-strange/tsubasa/assets/3332646/b8548383-d5e9-4823-a6ad-75844b141906

A horizontal scroll effect would be really fun here

---

Scoreboard needs to be smaller on mobile

<img width="1118" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/00c85b84-321a-465e-93ef-ecd84ae9c628">

---

**Resources**
 
[Components](https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=91%3A14639&mode=design&t=XTyAVzOoyY9iAsMt-1)

[Pages](https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=74%3A17685&mode=design&t=XTyAVzOoyY9iAsMt-1)

**Comment by ElegantShinobi** [comment]
YOOOO thé ANIMATION!? absolutely killing it

**Comment by clicksave** [comment]
Fonts:

**New airport**

[New Airport.zip](https://github.com/keep-starknet-strange/tsubasa/files/12283978/New.Airport.zip)

**Comment by YohanTz** [comment]
Looks cool! @LucasLvy what are the acceptance criteria for this one?

**Comment by LucasLvy** [comment]
all the score boards are integrated and they are displayed one after the other ?

**Comment by YohanTz** [comment]
> all the score boards are integrated and they are displayed one after the other ?

Ok, looks good ! I can take this one
