### ISSUE TITLE
Modify card struct to reflect the game rules

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/tsubasa#19]
# Description

Currently the card struct has some fields but they no longer reflect the game rules. Each card should have dribble/defense stats as well as a role. It should also have a field to differentiate the captain from the others.  The captain should have +1/+1.

# Acceptance criteria

* The cards have all the attributes

**Comment by hypekn1ght** [comment]
I can take this ser

**Comment by WhoIsNac** [comment]
I can handle this too if needed

**Comment by LucasLvy** [comment]
this one is already taken, can you pick another one plz @WhoIsNac
