### ISSUE TITLE
Implement turn check

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/tsubasa#22]
# Description

This game is a turn by turn game so one has to wait for his turn to play.

# Acceptance criteria

* Player one can only play during the even number turns
* Player two can only play during the odd number turns

**Comment by TeddyNotBear** [comment]
Can I take this ?

**Comment by dbejarano820** [comment]
Can I take this one? I believe Teddy already has one assigned

**Comment by dbejarano820** [comment]
@LucasLvy 

This logic would live inside the `attack_system` and also the `place_card_system right` ? Validating whether it's actually the players turn to play or not

**Comment by LucasLvy** [comment]
Yes and also in the `end_turn` system

**Comment by LucasLvy** [comment]
Any news there ?

**Comment by dbejarano820** [comment]
sorry for the delay, started looking into dojo last night

**Comment by LucasLvy** [comment]
Fixed by #71
