### ISSUE TITLE
Implement `place_card` logic

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/tsubasa#23]
# Description

According to the game rules when a player plays a card it has to wait for his next turn to enter the field. When a user places a card, save it in a buffer and in the `end_turn` system check if the buffer has any card that needs to be placed on the field.
This issue needs #21 to be fixed first

# Acceptance criteria

* When a card is placed it waits for the next player turn to go onto the field
* Energy cost of the card is deducted from the player's energy

**Comment by Falco90** [comment]
Hi, can I take this issue? :)

**Comment by LucasLvy** [comment]
Any news there ?

**Comment by hypekn1ght** [comment]
Gm i can take this one
