### ISSUE TITLE
Implement card buff if it's placed in its role

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/tsubasa#24]
# Description

Each card has a specific role, if a card is placed on the corresponding role on the field it has a +1/+1 buff. For example if a 3/4 goalkeeper is placed on the goalkeeper slot it'll be buffed to 4/5.

# Acceptance criteria

* A card is buffed if it's played on it's role slot.

**Comment by Matth26** [comment]
Can I take this one?

**Comment by LucasLvy** [comment]
Any news there ?

**Comment by hypekn1ght** [comment]
also this one if no one is doing it :)

**Comment by Matth26** [comment]
I was waiting for the #23 to be completed in order to have the data structure about card placement. But maybe I missed something.
I wanted to add this in the end_turn system, after the card is placed check if the placement match the card's role and boost the card if so.

**Comment by LucasLvy** [comment]
hey any progress here ? You just need to a `match` in the place card system and increase the stats if the 2 roles match

**Comment by Matth26** [comment]
Yes sorry I was waiting for the code where cards are placed on the field (at the start of next turn) but it was not required
