### ISSUE TITLE
Implement card energy logic

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/tsubasa#25]
# Description

As per the game rules each card costs a certain amount of energy. The energy is reset and incremented at each turn. Each player starts with 1 energy and is incremented each turn.

# Acceptance criteria

* Each player starts with 1 energy
* Energy is incremented by 1 at each of your turns
* Energy is reset at each of your turns

**Comment by TeddyNotBear** [comment]
Can i take this ?

**Comment by LucasLvy** [comment]
yes let's go !
