### ISSUE TITLE
Add color tokens in tailwind config 

### ISSUE THREAD

**Issue by ayushtom** [keep-starknet-strange/tsubasa#41]
Currently we are using colors from the figma file and there is no base design system prepared to use pre-decided colors for the whole app. We need to implement these for colors so that no unexpected shades come during development.

**Comment by dbejarano820** [comment]
i got this

**Comment by ayushtom** [comment]
@dbejarano820  Co-ordinate with the designer once to check if this is defined yet. You might be blocked on this if tokens are still being finalised

**Comment by dbejarano820** [comment]
@ayushtom great call
