### ISSUE TITLE
Implement `create_deck`

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/tsubasa#48]
# Description

Each player will need to create his deck. Each deck is composed of 8 different cards. A card is an NFT so a deck can be represented as a list of u256. Though any other way could be fine. Surprise me i guess 

# Acceptance criteria

* A user can create a deck

**Comment by hypekn1ght** [comment]
I can take this one ser

**Comment by hypekn1ght** [comment]
so for create_deck, does this check for card NFTs that the player has? 

And then maybe a function that sets the NFTs ids into the deck ?
