### ISSUE TITLE
Card design

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/tsubasa#5]
# Description

According to the [game rules](https://github.com/keep-starknet-strange/tsubasa/discussions/2#discussioncomment-6567694) we need to design multiple cards (depending on the rarity).
Each card will have at least:
* Player name
* Attack
* Defense
* Image of the player

# Acceptance criteria

* We'll schedule a meeting with Starkware/Dojo/Designer to validate the design

**Comment by clicksave** [comment]
Heres a rough wireframe of a card in 'preview mode. UI needs some attention but think this structure could work

If you have any specific comments that are difficult to communicate in a github reply you can leave them directly in the [figma file](https://www.figma.com/file/TmXdIgV2kEHLDJvojD2uhv/Tsubasa.app?type=design&node-id=1%3A2&mode=design&t=7VdsKLDHNh9ije2r-1)

**Card Preview**

Clicking on the card brings it up in a preview page where we can expose some extra information about it. 

<img width="1097" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/c413b712-2b53-4448-9cf5-3a24c8f7eead">

Top Right: Energy Cost
Bottom Left: Defense
Bottom Right: Offense

Question: Do cards have abilities?
Question: Should we start with a limited pool of cards for a demo?
Thought: Maybe theres a way where we can determine the level of their attributes via their stats.

---

**Comment by LucasLvy** [comment]
> Question: Do cards have abilities?

Not yet we start with a simple version and if we have enough time we can add them

> Should we start with a limited pool of cards for a demo?

I think so, maybe 22 cards or something ?

> Thought: Maybe theres a way where we can determine the level of their attributes via their stats.

Good question, worst case we can check the fifa stats

**Comment by clicksave** [comment]
OK Update. have a set of components that go into some of the different states. Ideally the attributes (dribble, defense, would be dynamic numbers rendered on top of the NFT its self. but check it out and let me know what you think. 

For guidance on how I'm imagining these cards interact with the board, see this comment in the card design discussion 

https://github.com/keep-starknet-strange/tsubasa/discussions/11#discussioncomment-6660892

---

**Resources**

[Components](https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=74%3A16940&mode=design&t=XTyAVzOoyY9iAsMt-1)

[Patterns](https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=136%3A42246&mode=design&t=XTyAVzOoyY9iAsMt-1)

**Comment by hypekn1ght** [comment]
these are lookin amazing

**Comment by clicksave** [comment]
Here's the set of final illustrations for the players, not sure if theres an ideal size, but can produce these larger and smaller if necessary 

<img width="1098" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/53e908f7-89c9-4fc1-bbd4-cffc915b73f3">

[@1x.zip](https://github.com/keep-starknet-strange/tsubasa/files/12290836/%401x.zip)

**Comment by clicksave** [comment]
Updated the way we're surfacing attributes and introduced a 'Damaged' state

<img width="823" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/dfe50752-1fcb-4481-bb1c-f517c02d4d5e">

---

**Resources**

https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=74%3A17361&mode=design&t=SzoYmXTd0QhKoFbs-1

**Comment by clicksave** [comment]
Colors: 
<img width="402" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/7ff1157b-d842-41f0-a7f4-1bf20597af84">

**Comment by remiroyc** [comment]
I can help to start the frontend integration of game card

**Comment by remiroyc** [comment]
#65 should be merged before
