### ISSUE TITLE
Implement card waiting on the side before entering the field

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/tsubasa#50]
# Description

Do what @clicksave shows

# Acceptance criteria

* There is a queue on the side of the field where each card will wait before entering the field to go to its slot
* There is an animation when the cards go from the side of the field to their slot

**Comment by ayushtom** [comment]
can i pick this? @LucasLvy

**Comment by clicksave** [comment]
Hopefully this is useful to you. When cards are placed on the board they enter a pending state which lasts for a full turn. visually It's a bit different that what lucas described but the practical effect is the same.

https://github.com/keep-starknet-strange/tsubasa/assets/3332646/86feb152-7ecb-447a-9032-303e8b934977

NOTE: Players are dragging and dropping cards here, and the card position has its own emphasized state

---

Resources 

[Pattern](https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=716%3A56650&mode=design&t=YFrj26sxlDo11ffc-1)
[Card Components](https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=74%3A17361&mode=design&t=YFrj26sxlDo11ffc-1)

**Comment by ayushtom** [comment]
Thank you! I'll look into this

**Comment by remiroyc** [comment]
@clicksave @ayushtom FYI I implemented a pending state on my card component #59

**Comment by ayushtom** [comment]
Thanks. Ill use this component and integrate on my PR or is anything pending to be done in this?

**Comment by remiroyc** [comment]
> Thanks. Ill use this component and integrate on my PR or is anything pending to be done in this? @remiroyc

Okay nice. I've just marked my PR as ready to review. It should be merged soon if everything goes well.
