### ISSUE TITLE
Attack animation + Out of the field animation

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/tsubasa#51]
# Description

The cards will try to pass each other and if a card is passed it goes out of the field we need to reflect that in the frontend

# Acceptance criteria

* There is an animation when the cards attack
* There is an animation when a card goes out of the field.

**Comment by Cheelax** [comment]
taking this one

**Comment by Cheelax** [comment]
Will try using this lib: https://www.react-spring.dev/
