### ISSUE TITLE
Implement create_card system

### ISSUE THREAD

**Issue by WhoIsNac** [keep-starknet-strange/tsubasa#63]
### Description

Each card must be created in the game(According to their stats) , we need a create_card system to create each card in order to make the player deck.

When a card is created it is assigned to each player’s deck in order to compose their team.

**Comment by Falco90** [comment]
I can take this issue

**Comment by WhoIsNac** [comment]
Sorry, the issue has already been resolved with the PR https://github.com/keep-starknet-strange/tsubasa/pull/69
