### ISSUE TITLE
Build the home page

### ISSUE THREAD

**Issue by clicksave** [keep-starknet-strange/tsubasa#77]
OK lfg, put together a mockup for the home page it's a little more streamlined than the current one and integrates the deck builder

https://github.com/keep-starknet-strange/tsubasa/assets/3332646/2943c08b-c30b-4a73-a100-dce93637617c

Site navigation is available in tabs in the footer

---

Here's a full view of the page

<img width="617" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/513f9ab5-da19-4e1d-9d59-5bb26fd3e089">

---

There are a few differences between the desktop and mobile renderings

<img width="233" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/f1124ab3-ff76-431b-8966-cce7c42a2c35">

namely the hero graphic, social link renderings, logo, and the game board asset

---

**Resources**

[Pages](https://www.figma.com/file/CC8hm73vxTkXSt3b5NWKvX/Tsubasa-UI-Kit?type=design&node-id=1118%3A238365&mode=design&t=eo1CLODQx5VrPUjC-1)

**Comment by clicksave** [comment]
Theres a 'rules' button. Thinking this can bring up the full ruleset in a modal. or possibly like to the rules page in github. 

<img width="1480" alt="image" src="https://github.com/keep-starknet-strange/tsubasa/assets/3332646/e14d4240-486b-4be0-81e2-6e809fefe9ad">

**Comment by notV4l** [comment]
i started this one
